### ISSUE TITLE
AI assistant demo - bug list

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_build_deploy#52]
1. onnx == 1.16.1 in the requirements.txt
2. AUTO plug should be disabled
3. Refactor all configurations to chatbot.config

**Comment by raymondlo84** [comment]
@adrianboguszewski

**Comment by raymondlo84** [comment]
start over - does not remove history properly. A refresh of the browser will remove history instead.

**Comment by raymondlo84** [comment]
whipser won't' run on NPU, and gives wrong output with GPU....

Have we tested this instead?
https://huggingface.co/distil-whisper/distil-medium.en

**Comment by raymondlo84** [comment]
https://huggingface.co/distil-whisper/distil-large-v3 looks like this one is already fastest? Rel. Latency is like 6.3x faster.

Did we benchmark this yet?

**Comment by raymondlo84** [comment]
https://github.com/raymondlo84/openvino_build_deploy/tree/bartender/demos/bartender_assistant_demo 

I made some changes and uploaded here.

**Comment by raymondlo84** [comment]
"llama-3.1-8b-instruct": {
            "sym": True,
            "group_size": 128,
            "ratio": 1.0,
        },

https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/llm-chatbot/llm-chatbot.ipynb

For Llama 3.1 we should use this config. Kate told me the engineer measured this is the best performance vs accuracy trade off.

**Comment by adrianboguszewski** [comment]
> start over - does not remove history properly. A refresh of the browser will remove history instead.

You're right. Fixed.

> https://huggingface.co/distil-whisper/distil-large-v3 looks like this one is already fastest? Rel. Latency is like 6.3x faster.
> 
> Did we benchmark this yet?

This model is used by default.

**Comment by raymondlo84** [comment]
Ok, it's the INT8. I turned that off and now Whisper can run on GPU without giving me garbage output!!

I made a branch called bartender, and you can check out the changes I made.

**Comment by raymondlo84** [comment]
and it runs < 2seconds now!! so much faster than 8 seconds on CPU.

**Comment by raymondlo84** [comment]
If you leave the application running for 10 minutes (idle), the next time recording with microphone will create a huge spike of CPU usage and ram usage. It takes maybe 30 seconds before it finish processed a 5 seconds recording.

**Comment by raymondlo84** [comment]
https://www.gradio.app/guides/real-time-speech-recognition maybe should look into the real-time transcribing part so we don't have to worry about latency

**Comment by adrianboguszewski** [comment]
> * AUTO plug should be disabled
> * Refactor all configurations to chatbot.config

This gives me hallucinations back. I decided to stay with the current config.

> AUTO plug should be disabled

Removed

> Refactor all configurations to chatbot.config

Configuration moved to personality.yaml. Please note, it means the demo name and path has changed - it's no longer a healthcare assistant but virtual AI assistant
