### ISSUE TITLE
2024.4 support on all demos

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_build_deploy#72]
We need a quick update on all requirements.txt 

maybe it is a good time to write a simple CI/CD python code to run the demo on a server for sanity check.

-ray

**Comment by adrianboguszewski** [comment]
@raymondlo84 demos updated. Do you mean also AI Ref Kits?

**Comment by raymondlo84** [comment]
> @raymondlo84 demos updated. Do you mean also AI Ref Kits?

Ideally yes

**Comment by adrianboguszewski** [comment]
@riacheruvu @zhuo-yoyowz please check your AI Ref Kits

**Comment by adrianboguszewski** [comment]
Closing as already addressed.
