### ISSUE TITLE
Virtual Assistant Microphone Recording = Huge lag or Freezing 

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_build_deploy#84]
I think there is a bug in Windows when we trigger the microphone recording. To repeat this bug, run the virtual assistant chatbot and use the text mode. After a few minutes later try the microphone recording mode and the interface will freeze (very high RAM + CPU usage) and eventually will work.

It seems like the browser or so cached lots of audio buffers and it was trying to clean it.

**Comment by adrianboguszewski** [comment]
I bet it's gradio issue. Try to upgrade it and see if it still happens?

**Comment by raymondlo84** [comment]
Are we sure we are using Gradio correctly?

**Comment by adrianboguszewski** [comment]
Depends on what you mean. What doesn't look correct?
